---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(ggplot2)
library(here)
```

```{r}

age_and_sex <- read_csv("../clean_data/clean_age_and_sex.csv")

```

```{r}
age_and_sex %>% filter(HBName == "NHS Ayrshire and Arran" & Sex == "Male" & Age == "50-59 years") %>% 
  ggplot(aes(x = Quarter, y = AverageLengthOfStay, group = AdmissionType, colour = AdmissionType)) +
  geom_point()+
  geom_line(size = 1)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```



```{r}
age_and_sex %>% filter(HBName == "NHS Ayrshire and Arran" & Sex == "Female" & Age == "40-49 years") %>% 
  ggplot(aes(x = Quarter_single, y = AverageLengthOfStay, fill = AdmissionType, colour = AdmissionType)) +
  geom_col(position = "dodge", colour = "white")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~ Year)+
  labs(
    title = "\nAverage length of hospital stay by admission type\n",
    x = "\nQuarter\n",
    y = "\nAverage length of stay (days)\n"
    
  )

```



```{r}
age_and_sex %>% group_by(Quarter, Age) %>% summarise(number_admissions = sum(Stays)) %>% 
  ggplot()+
  geom_vline(xintercept = "2020Q2", size = 1.5, colour = "red")+
  annotate("rect", xmin = 1, xmax = 3, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue" ) +
  annotate("rect", xmin = 5, xmax = 7, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue") +
  annotate("rect", xmin = 9, xmax = 11, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue") +
  annotate("rect", xmin = 13, xmax = 15, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue") +
  annotate("rect", xmin = 17, xmax = 19, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue") +
  annotate("rect", xmin = 21, xmax = 22, ymin = 0, ymax = 35000, alpha = 0.3, fill = "lightblue") +
  geom_line(aes(x = Quarter, y = number_admissions, group = Age, colour = Age), size = 1.5)+
  scale_y_continuous(labels = scales::comma)+
  theme_minimal()+
scale_colour_manual(values = c("#1F3F49","#488A99" ,"#1C4E80","#4cb5f5" ,"#A5d8DD", "#EA6A47" ,"#7E909A", "#AC3E31", "#484848", "#DBAE58", "#20283E"  ))+
  
theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
      axis.text.y = element_text(size = 20),
      title  = element_text(size = 20, face = "bold") 
 
      )+
   labs(
    title = "\nHospital Admissions by Age\n", 
    x = "\nQuarter\n", 
    y = "\nNumber of Admissions\n"
  )
```

Hospital admissions by gender

```{r}
age_and_sex %>% group_by(Quarter, Sex) %>% summarise(number_admissions = sum(Stays)) %>% 
  ggplot()+
  geom_line(aes(x = Quarter, y = number_admissions, group = Sex, colour = Sex), size = 1.5)+
theme(axis.text.x = element_text(angle = 45, hjust = 1))+
   labs(
    title = "Hospital Admissions by Gender"
  )
```

more in line

```{r}
#pre-covid and post-covid - doesn't make sense as more 

covid <-age_and_sex %>% mutate(pre_covid = if_else(Quarter %in% c("2017Q4", "2018Q1", "2018Q2"," 2018Q3", "2018Q4", "2019Q1", "2019Q2", "2019Q3", "2019Q4", "2020Q1"), TRUE, FALSE))

pre_covid <- age_and_sex %>% mutate(pre_covid = if_else(Quarter %in% c("2017Q4", "2018Q1", "2018Q2"," 2018Q3", "2018Q4", "2019Q1", "2019Q2", "2019Q3", "2019Q4", "2020Q1"), TRUE, FALSE)) %>% filter(pre_covid == TRUE)

after_covid <- age_and_sex %>% mutate(pre_covid = if_else(Quarter %in% c("2017Q4", "2018Q1", "2018Q2"," 2018Q3", "2018Q4", "2019Q1", "2019Q2", "2019Q3", "2019Q4", "2020Q1"), TRUE, FALSE)) %>% filter(pre_covid == FALSE)

 covid %>% filter(HBName == "NHS Ayrshire and Arran" & Sex == "Male") %>% 
   group_by(pre_covid, Quarter_single) %>%
   summarise(number_admissions = sum(Stays)) %>% 
   
  ggplot(aes(x = Quarter_single, y = number_admissions, fill = pre_covid))+
  geom_col(position = "dodge")
    
```

pre-covid, post_covid - length of stay

```{r}
age_and_sex %>% filter(HBName == "NHS Ayrshire and Arran" & Sex == "Female" & Age == "40-49 years") %>% 
  ggplot(aes(x = Quarter_single, y = AverageLengthOfStay, fill = AdmissionType, colour = AdmissionType)) +
  geom_col(position = "dodge", colour = "white")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~ Year)+
  labs(
    title = "\nAverage length of hospital stay by admission type\n",
    x = "\nQuarter\n",
    y = "\nAverage length of stay (days)\n"
    
  )
```

