---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(infer)

data <- clean_names(read_csv(here("raw_data/inpatient_and_daycase_by_nhs_board_of_treatment_age_and_sex.csv")))
```
```{r}
data %>% 
  filter(is.na(average_length_of_stay_qf)) %>% 
  distinct(average_length_of_stay)
```

```{r}
data %>% 
  filter(
    admission_type == "All Inpatients" & 
      str_detect(quarter, "201")
  ) %>% 
  ggplot(aes(average_length_of_stay)) +
  geom_histogram()
```

```{r}
bootstrap_resample <- data %>% 
  filter(admission_type == "All Inpatients" & str_detect(quarter, "201")) %>% 
  select(average_length_of_stay) %>% 
  specify(response = average_length_of_stay) %>% 
  generate(reps = 10000, type = "bootstrap") %>% 
  calculate(stat = "mean")

bootstrap_ci <- bootstrap_resample %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_resample %>% 
  visualise(bins = 30) +
  shade_ci(bootstrap_ci)

bootstrap_ci

```
```{r}
mean_stay <- data %>% 
  filter(admission_type == "All Inpatients" & str_detect(quarter, "201")) %>% 
  summarise(avg_stay = mean(average_length_of_stay, na.rm = TRUE)) %>% 
  pull()

upper_ci <- bootstrap_ci %>% 
  select(upper_ci) %>% 
  pull()

lower_ci <- bootstrap_ci %>% 
  select(lower_ci) %>% 
  pull()
```



```{r}
data %>% 
  filter(admission_type == "All Inpatients" & str_detect(quarter, "201")) %>% 
  summarise(avg_stay = mean(average_length_of_stay, na.rm = TRUE))
```

```{r}
data %>% 
  # admission type, health board, age, sex, quarter
  filter(
    admission_type == "Elective Inpatients" & 
      !is.na(hbqf) & 
      age == "10-19 years" &
      sex == "Female"
    #str_detect(quarter, "202")
  ) %>% 
  group_by(quarter, sex) %>% 
  summarise(avg_stay = mean(average_length_of_stay)) %>% 
  ggplot(aes(quarter, avg_stay, fill = sex)) +
  geom_line(group = 1) +
  #geom_rect(aes(ymax = upper_ci, ymin = lower_ci, xmin = 0, xmax = Inf), fill = "red", alpha = 0.2) +
  #geom_hline(aes(yintercept = mean_stay)) +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
data %>% 
  # admission type, health board, age, sex, quarter
  filter(
    admission_type == "All Inpatients" & 
      !is.na(hbqf) &
      age == "40-49 years" &
      str_detect(quarter, "201")
  ) %>% 
  summarise(avg_stay_2 = sum(length_of_stay)/sum(stays)) %>% 
  pull()
```


```{r}
data %>% 
  mutate(time = quarter,
         year = str_extract(quarter, "[0-9]{4}"),
         quarter = str_remove(quarter, "[0-9]{4}"))

```


```{r}
length_of_stay_data <- read_csv(here("clean_data/length_of_stay_data.csv"))
```

```{r}
length_data <- length_of_stay_data %>% 
  filter(
    admission_type == "Emergency Inpatients" &  
      hb_name == "All Scotland" & 
      age == "40-49 years" &
      sex == "Female" &
      !str_detect(quarter, "2017")
    #str_detect(quarter, "202")
  ) %>% 
  group_by(quarter) %>% 
  summarise(avg_stay = sum(length_of_stay)/sum(stays)) %>% 
  mutate(time = quarter,
         year = str_extract(quarter, "[0-9]{4}"),
         quarter = str_remove(quarter, "[0-9]{4}"))
  
  years <- unique(length_data$year)
```

```{r}
length_data %>% 
  ggplot(aes(interaction(quarter, year), avg_stay), size = 5) +
  geom_line(group = 1, size = 2) +
  geom_point(size = 3) +
  annotate("text", x = seq_len(nrow(length_data)),
           y = min(length_data$avg_stay)-0.7,
           label = length_data$quarter) +
  annotate("text", x = 1 + 4 * (0:(length(years)-1)),
           y = min(length_data$avg_stay)-1.3,
           label = years) +
  coord_cartesian(ylim = c(min(length_data$avg_stay), 7.5),
                  clip = "off") +
  geom_vline(xintercept = 9, size = 1.5, colour = "red") +
  
  scale_colour_manual(name = "", # Add legend
                      breaks = "Pre-covid 2018-2019 Average",
                      values = c("Pre-covid 2018-2019 Average" = "red")) +
  theme(
    text = element_text(size = 15),
    axis.text.x = element_blank(),
    axis.title.x = element_text(vjust = -8),
    plot.margin = unit(c(1, 1, 6, 1), "lines")
  ) +
  labs(
    title = "Average length of stay",
    x = "Quarter",
    y = "Average Length of Stay (days)"
  )
```

```{r}
data %>% 
  filter(admission_type %in% c("Emergency Inpatients", "Elective Inpatients", "All Inpatients")) %>% 
  summarise(max(average_length_of_stay, na.rm = TRUE))
```
```{r}
data %>% 
  filter(average_length_of_stay == 601.6)
```

